### ISSUE TITLE
Configuring multiple ports and/or paths

### ISSUE THREAD

**Issue by erapade** [lmagyar/homeassistant-addon-tailscale#118]
Well, this is not an issue, rather a feature request or request for help/advise

I came across this and it might do what I'm looking for but I can't see how I would be able to configure it using the GUI 
https://www.reddit.com/r/Tailscale/comments/14gccua/funnel_serve_multiple_ports/?rdt=45747
Is this possible using this fork and how could it be done using the GUI or the command line

I said it looks like it will do what I'm looking for but maybe not completely. What I would like to do is to be able to connect to other network nodes so that I instead of connecting to 127.0.0.1 are connecting to e.g 192.168.0.10 (in my case a ESPHome based device or even my router since I'm behind a NAT:ed ISP network). And I need to use the funnel feature because I sometimes can't connect from a Tailscale equiped device

So maybe doing this:
tailscale serve https:443 /homeassistant http://127.0.0.1:8123
tailscale serve https:443 /device1 http://192.168.0.22:80
tailscale serve https:443 /router http://192.168.0.1:80
tailscale funnel 443 on

or if not working:
tailscale serve https:443 / http://127.0.0.1:8123
tailscale funnel 443 on
tailscale serve https:8443 / http://192.168.0.22:80
tailscale funnel 8443 on
tailscale serve https:10000 / http://192.168.0.1:80
tailscale funnel 10000 on

**Comment by lmagyar** [comment]
There is no GUI in the add-on to configure multiple serve/funnel ports, because it is planned by Tailscale that they will make one in the future (but don't wait for it)... :)

What I suggest (it is possible with the official add-on also):
- enable the built in proxy/funnel feature of the add-on and see if it works (check the docs for proxy to see the required config changes in HA and Tailscale), if it works, disable it
- access HA's command line (eg. with the SSH add-on) and go to the Tailscale add-on's command line with ``docker exec -it `docker ps -q -f name=tailscale` /bin/bash``
- here you can use `/opt/tailscale serve --bg ...` or `/opt/tailscale funnel --bg ...` to configure serve/funnel permanently (it will survive an add-on restart, and the permanent config will be part of the backup also)
- but 127.0.0.1 is a Tailscale limitation, it can forward traffic only to this interface, so I suggest to start an NGINX add-on and forward some local ports/paths (eg. 127.0.0.1:8888/device1 -> xxx) to your other destinations and Tailscale serve/funnel can access this NGINX proxy (eg. on port 8888 above)
- but note: after funnel is set up this way, anybody on the internet can access your router's internal web interface

**Comment by lmagyar** [comment]
Oh, and tailscale funnel's cli syntax has changed (they made a mixed mess with serve), see https://tailscale.com/kb/1311/tailscale-funnel

You need only 3 funnel commands (no serve needed), like: `/opt/tailscale funnel --bg --https=443 --set-path=/homeassistant http://127.0.0.1:8123`

**Comment by lmagyar** [comment]
Closing, because there is no reply whether it was successful.
