### ISSUE TITLE
Continuous restart of the new version 

### ISSUE THREAD

**Issue by martusi61** [lmagyar/homeassistant-addon-tailscale#19]
With the latest version the addon keeps restarting with the error shown in the attachment, even though I haven't changed anything in my home assistant configuration. 
![Screenshot_20230427-125201~2](https://user-images.githubusercontent.com/51626288/234844282-79b6e3c0-53bf-4a5c-958c-e45f79627069.png)

**Comment by lmagyar** [comment]
Yes: the Tailscale HTTPS->HTTP proxy can't access HA through plain HTTP. The connection between HA and the Tailscale add-on must be unencrypted, because Tailscale's proxy will connect to HA through 127.0.0.1, but the current cert HA serves in your case is for another "domain", and Tailscale's proxy will drop the connection with `proxy error: x509: cannot validate certificate
for 127.0.0.1 because it doesn't contain any IP SANs`.

This previously just caused some warning, but I changed it, because I was asked to stop the add-on in this case by the original developer of the Tailscale add-on when he reviewed my PR (still not merged).

The question what is the situation?
- Do you enabled HTTPS on Tailscale's admin console, but you don't want to access HA through Tailscale's HTTPS url/cert, you use HTTPS only on other machines? So you would like to disable Tailscale's Proxy and Funnel on this machine, ie. in the add-on config? (currently there is no config for this, that's why I ask about the situation)
- Or is this just a wrong config: you configured HA to use a cert eg. from DuckDNS? In this case see the documentation: configure HA to use plain HTTP, and use eg. NGINX add-on to use the DuckDNS cert. HA will be available through Tailscale's url and Tailscale's https/cert on `https://<your-device-name>.tailxxxx.ts.net`, on the default 443 port. - If Funnel is also enabled, you can use this url on any machine, even without Tailscale's VPN client: Tailscale will TCP-proxy the connection between the internet and your VPN, see Funnel documentation.

**Comment by martusi61** [comment]
Indeed, as I thought, however I have https on Duckdns classic home assistant. That being the case I think I'll switch to the old tailscale or better a cloudflare solution.Thanks for the quick response and all you do here on GitHub.

**Comment by lmagyar** [comment]
Same situation for me, DuckDNS+NGINX proxy is my main connection and Tailscale is the backup.

Don't you want to use Tailscale's certificate+url+https Proxy? Without it you can access HA on the current port, like `https://<your-device-name>.tailxxxx.ts.net:8123`, but the browser will warn you, that the certificate is invalid. The Tailscale Proxy is exactly for this situation, you can access HA without the browser warning, on the same url, but on the default port, like `https://<your-device-name>.tailxxxx.ts.net:` (note: no port number at the end, Tailscale Proxy in the add-on will forward the traffic to HA).

A lot of people waited for this Proxy feature (and for Funnel), so I'm really interested why is it not useful for your setup/config, or how should I make it usable? Eg. add an option to disable it optionally?

When my PR will be merged into the official Tailscale add-on, it is better to not break current configurations out there. :)

**Comment by martusi61** [comment]
Thank you, you are not right, but I have my own domain already registered and I would like to use that, also in order to avoid any problems with external URLs with Duckdns , Cloudflare guarantees me this.

**Comment by lmagyar** [comment]
OK, as I understand, you would like to make this by default enabled Tailscale Proxy/Funnel feature to be optionally disabled, because Cloudflare provides a very similar solution.

**Comment by martusi61** [comment]
Yes, I will uninstall tailscale, with Cloudflare I can use my already registered personal domain which I also use for my old website

**Comment by lmagyar** [comment]
I've added an optional bool config `proxy: bool?` to optionally disable Tailscale's Proxy and Funnel features in case somebody else runs into similar situation.

This is like the original add-on's `advertise_exit_node: bool?` or `taildrop: bool?` options, disable something in case somebody has issues with it.

I will release it soon.

**Comment by lmagyar** [comment]
New release is out, closing this now.
And thank you for reporting the issue.

**Comment by martusi61** [comment]
Great idea, I'll try it anyway. Thanks again for your work on GitHub.
